version: 2

references:
  set_environment_variables: &set_environment_variables
    run:
      name: Set Environment Variables
      command: |
        echo 'export CI_SHA1=$CIRCLE_SHA1' >> ${BASH_ENV}
        echo 'export CI_BRANCH=$CIRCLE_BRANCH' >> ${BASH_ENV}
        echo 'export CI_BUILD_NUM=$CIRCLE_BUILD_NUM' >> ${BASH_ENV}
        echo 'export CI_TAG=$CIRCLE_TAG' >> ${BASH_ENV}
        echo 'export ROK8S_INSTALL_PATH=${HOME}' >> ${BASH_ENV}
        echo "export KUBECONFIG_DATA=\$$KUBECONFIG_DATA" >> ${BASH_ENV}

  deploy_steps: &deploy_steps
    docker:
      - image: quay.io/reactiveops/ci-images:v7.15.0-alpine
    steps:
      - checkout
      - *set_environment_variables
      - run: prepare-kubectl
      - run: k8s-deploy-and-verify -f ${ROK8S_CONFIG}

jobs:
  imagebuild:
    docker:
      - image: quay.io/reactiveops/ci-images:v7.15.0-alpine
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - run: "[[ -n ${ROK8S_NO_BUILD} ]] || docker-pull -f ${ROK8S_CONFIG}"
      - run: "[[ -n ${ROK8S_NO_BUILD} ]] || docker-build -f ${ROK8S_CONFIG}"
      - run: "[[ -n ${ROK8S_NO_BUILD} ]] || docker-push -f ${ROK8S_CONFIG}"
    environment:
      ROK8S_CONFIG: deploy/staging.config
  deploy_development:
    <<: *deploy_steps
    environment:
      ROK8S_CONFIG: deploy/development.config
      KUBECONFIG_DATA: KUBECONFIG_DATA_DEVELOPMENT
  deploy_staging:
    <<: *deploy_steps
    environment:
      ROK8S_CONFIG: deploy/staging.config
      KUBECONFIG_DATA: KUBECONFIG_DATA_STAGING
  deploy_production:
    <<: *deploy_steps
    environment:
      ROK8S_CONFIG: deploy/production.config
      KUBECONFIG_DATA: KUBECONFIG_DATA_PRODUCTION

workflows:
  version: 2
  build_default:
    jobs:
    - imagebuild:
        context: org-global
        filters:
          tags:
            ignore: /.*/
    - deploy_development:
        context: org-global
        requires:
          - imagebuild
        filters:
          branches:
            only:
              - develop
          tags:
            ignore: /.*/
    - deploy_staging:
        context: org-global
        requires:
          - imagebuild
        filters:
          branches:
            only:
              - master
          tags:
            ignore: /.*/
    - deploy_production:
        context: org-global
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /\d+\.\d+\.\d+$/
