version: 2

references:
  set_environment_variables: &set_environment_variables
    run:
      name: Set Environment Variables
      command: |
        echo 'export CI_SHA1=$CIRCLE_SHA1' >> ${BASH_ENV}
        echo 'export CI_BRANCH=$CIRCLE_BRANCH' >> ${BASH_ENV}
        echo 'export CI_BUILD_NUM=$CIRCLE_BUILD_NUM' >> ${BASH_ENV}
        echo 'export CI_TAG=$CIRCLE_TAG' >> ${BASH_ENV}
        echo 'export ROK8S_INSTALL_PATH=${HOME}' >> ${BASH_ENV}

  build_image: &build_image
    run:
      name: Build Docker Image
      command: |
        docker login quay.io -u="${quay_robot}" -p="${quay_token}"
        docker-pull -f deploy/production.config
        docker-build -f deploy/production.config

  deploy: &deploy
    run:
      name: Deploy to Production
      command: |
        docker-push -f deploy/production.config
        prepare-kubectl
        k8s-deploy-and-verify -f deploy/production.config

jobs:
  build_image:
    docker:
      - image: quay.io/reactiveops/ci-images:v9.0-stretch
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - *build_image
  deploy:
    docker:
      - image: quay.io/reactiveops/ci-images:v9.0-stretch
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - *build_image
      - *deploy

workflows:
  version: 2
  build:
    jobs:
      - build_image
      - deploy:
          requires:
            - build_image
          filters:
            branches:
              only: master
